// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginInput struct {
	LoginText string `json:"login_text"`
	Password  string `json:"password"`
}

type Mutation struct {
}

type NewUser struct {
	FirstName *string `json:"first_name,omitempty"`
	LastName  string  `json:"last_name"`
	Username  *string `json:"username,omitempty"`
	Email     string  `json:"email"`
	Password  *string `json:"password,omitempty"`
}

type Query struct {
}

type User struct {
	ID        string  `json:"id"`
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Username  *string `json:"username,omitempty"`
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	Token     string  `json:"token"`
}
